name: CI - Unit Tests

on: [push]

jobs:
  run-unit-tests:
    name: run-unit-tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with: 
        node-version: 18
        cache: 'npm'
    - run: npm ci
    - run: npm run test:unit
      env:
        PORT: 3000
        NODE_ENV: test
        DATABASE_URL: fake_url
        JWT_SECRET: fake_secret
        JWT_EXPIRES_IN: 86400
