name: CI - Integration and run-int-e2e-tests

on: [pull_request]

jobs:
  run-int-e2e-tests:
    name: run-unit-tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: bitnami/postgresql
        ports:
          - 5432:5432
        env:
          POSTGRESQL_USERNAME: postgres
          POSTGRESQL_PASSWORD: docekr
          POSTGRESQL_DATABASE: projectdb
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with: 
        node-version: 18
        cache: 'npm'
    - run: npm ci
    - run: npx prisma generate --schema ./src/shared/infrastructure/database/prisma/schema.prisma
      env:
        DATABASE_URL: "postgresql://postgres:docekr@localhost:5432/projectdb?schema=public"
    - run: npm run test:int
      env:
        PORT: 3000
        NODE_ENV: test
        DATABASE_URL: "postgresql://postgres:docekr@localhost:5432/projectdb?schema=public"
        JWT_SECRET: fake_secret
        JWT_EXPIRES_IN: 86400
    - run: npm run test:e2e
      env:
        PORT: 3000
        NODE_ENV: test
        DATABASE_URL: "postgresql://postgres:docekr@localhost:5432/projectdb?schema=public"
        JWT_SECRET: fake_secret
        JWT_EXPIRES_IN: 86400
